### ISSUE TITLE
Suggestions to edit text in README.md (Ikajung)

### ISSUE THREAD

**Issue by tm3917** [peachiia/open-heatpad-controller#1]
Under "Open Heat-Pad Controller":

(2nd sentence)
This project is an example of multi-tasking on an Arduino using a timer. I tried NOT to include OOP concept, to keep it as simple as possible for students. However, please feel free to improve it as you like.

Under "Terminal":

(3rd sentence)
If there are lots of numbers flooding on your screen, type 'stop' and press enter, to stop all tasks.

(4th sentence)
For first time usage, following these steps is recommended.

Under "Tested Hardware":

(spelling mistake)
In this sentence, "Thermistor is serially connected with 10k Ohms Resister between 5V and Ground Pin on MCU."

"Resister" should be changed to "Resistor"

**Comment by peachiia** [comment]
Thank you very much for the suggestions
